language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t archansy/react -f Dockerfile.Dev .

script:
  - docker run -e CI=true archansy/react npm run test  

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "AR_ReactApp"
  env: "ArReactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-980992176666"
  bucket_path: "AR_ReactApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY