version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile.Dev
        image: archansy/react:0.1
        ports:
            - "3000:3000" 
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true
        tty: true
             
